# Per-host module for justin-powerhouse — AMD Ryzen 7 5800X desktop,
# Radeon RX 7900 XTX (gfx1100), 2x NVMe.
#
#   - hardware-configuration.nix : generated by nixos-generate-config
#   - this file                  : hostname, nixos-hardware modules, swap unlock
#
# configuration.nix and home.nix are host-agnostic and shared.
{ inputs, lib, ... }:
{
  imports = [
    ./hardware-configuration.nix
    inputs.nixos-hardware.nixosModules.common-cpu-amd
    inputs.nixos-hardware.nixosModules.common-gpu-amd
    inputs.nixos-hardware.nixosModules.common-pc-ssd
  ];

  networking.hostName = "justin-powerhouse";

  # Swap is its own LUKS partition (nvme0n1p3). nixos-generate-config lists it
  # in swapDevices but emits no unlock for it, so without this it never
  # decrypts and stays at 0 B. No resumeDevice: desktop, not hibernating.
  boot.initrd.luks.devices."luks-14212e0a-ef39-40c7-97c0-b23dabff3db9".device =
    "/dev/disk/by-uuid/14212e0a-ef39-40c7-97c0-b23dabff3db9";

  # ESP is only ~1 GB here (Calamares default), and each generation writes a
  # kernel + initrd into it. Cap generations so /boot can't fill up.
  boot.loader.systemd-boot.configurationLimit = lib.mkForce 5;

  # Remote access for this desktop. openFirewall (default true) opens 22.
  services.openssh.enable = true;
  users.users.justin.openssh.authorizedKeys.keys = [
    "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIEGXrWva+3LnsW+j+SKHtLI575eHRFCvG0nVCDRqQmWu box-access"
  ];
}
