# Per-host module for justin-powerhouse — AMD Ryzen 7 5800X desktop,
# Radeon RX 7900 XTX (gfx1100), 2x NVMe.
#
#   - hardware-configuration.nix : generated by nixos-generate-config
#   - this file                  : hostname, nixos-hardware modules, swap unlock
#
# configuration.nix and home.nix are host-agnostic and shared.
{ inputs, lib, pkgs, ... }:
{
  imports = [
    ./hardware-configuration.nix
    ./llama-power.nix
    ./gpu-power.nix
    inputs.nixos-hardware.nixosModules.common-cpu-amd
    inputs.nixos-hardware.nixosModules.common-gpu-amd
    inputs.nixos-hardware.nixosModules.common-pc-ssd
  ];

  networking.hostName = "justin-powerhouse";

  # Swap (nvme0n1p3) uses a fresh random key each boot — no passphrase prompt at
  # boot, and no emergency-mode risk if an unlock is missed. No hibernation is
  # wanted, so swap contents need not persist. Configured via
  # swapDevices[].randomEncryption in hardware-configuration.nix; the LUKS header
  # Calamares wrote on p3 is now unused.


  # ESP is only ~1 GB here (Calamares default), and each generation writes a
  # kernel + initrd into it. Cap generations so /boot can't fill up.
  boot.loader.systemd-boot.configurationLimit = lib.mkForce 5;

  # Remote access for this desktop. openFirewall (default true) opens 22.
  services.openssh.enable = true;
  services.openssh.settings.PermitRootLogin = "no"; # root: TTY + su only, no SSH
  users.users.justin.openssh.authorizedKeys.keys = [
    "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFw01ML+s6M74ue7NAqaUOH8h5lxbxn8Q45Rnj+Y74Lr"
  ];
  # LLM weights on the second NVMe (nvme1n1, serial 26026B804673): a bare
  # whole-disk ext4 (no partition table), mounted by filesystem UUID so it can
  # never be confused with the identical-model OS drive. nofail: a missing or
  # failed models drive must never block boot. ~645 GB of GGUF files.
  fileSystems."/home/justin/models" = {
    device = "/dev/disk/by-uuid/302ef0d7-6f4c-41e6-993e-32075d85104e";
    fsType = "ext4";
    options = [ "nofail" "noatime" "x-systemd.device-timeout=10s" ];
  };

  # Direct llama.cpp on the RX 7900 XTX (gfx1100), ROCm/HIP backend. Pin the
  # GPU target so it builds for this arch only. render group for /dev/kfd.
  users.users.justin.extraGroups = [ "render" ];


  # Always-on box: never auto-suspend/hibernate — it must stay reachable over
  # SSH and keep serving LLMs while idle. The display still turns off and the
  # session still locks; only the machine sleeping is disabled. Unmask these if
  # you ever want manual suspend.
  systemd.targets.sleep.enable = false;
  systemd.targets.suspend.enable = false;
  systemd.targets.hibernate.enable = false;
  systemd.targets.hybrid-sleep.enable = false;

}
