# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usb_storage" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-1d39ff5e-1939-4d7c-abd3-833dbd4fa305";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-1d39ff5e-1939-4d7c-abd3-833dbd4fa305".device = "/dev/disk/by-uuid/1d39ff5e-1939-4d7c-abd3-833dbd4fa305";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/3DBC-3976";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-14212e0a-ef39-40c7-97c0-b23dabff3db9"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
